# Generated by Django 3.2 on 2022-06-07 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientxs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientx',
            name='cuit',
            field=models.CharField(max_length=11, unique=True, verbose_name='Cuit/Cuil'),
        ),
        migrations.AlterField(
            model_name='clientx',
            name='ingreso',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso'),
        ),
    ]
