# Generated by Django 3.2 on 2022-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientxs', '0002_auto_20220607_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientx',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Cuit/Cuil'),
        ),
    ]
