# Generated by Django 3.2 on 2022-04-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitudcuidadosrecurrencia_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Asignada'), (3, 'Finalizada'), (4, 'Cancelada')], default=1),
        ),
    ]
