# Generated by Django 3.2 on 2022-04-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitudcuidados_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='costo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='montoPagado',
            field=models.FloatField(null=True),
        ),
    ]
