# Generated by Django 3.2 on 2022-06-07 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_auto_20220425_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='costo',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo de referencia del servicio'),
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='montoPagado',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitudcuidadosrecurrencia',
            name='tiempo',
            field=models.IntegerField(blank=True),
        ),
    ]
