# Generated by Django 3.2 on 2022-06-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_auto_20220607_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidadosrecurrencia',
            name='tiempo',
            field=models.FloatField(blank=True),
        ),
    ]
