# Generated by Django 3.2 on 2022-06-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_alter_solicitudcuidadosrecurrencia_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidadosrecurrencia',
            name='tiempo',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
