# Generated by Django 3.2 on 2022-06-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_alter_solicitudcuidadosrecurrencia_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='costo',
            field=models.FloatField(blank=True, help_text='El costo es semanal', null=True, verbose_name='Costo del servicio'),
        ),
    ]
