# Generated by Django 3.2 on 2022-06-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0007_alter_solicitudcuidadosrecurrencia_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidadosfechas',
            name='tiempo',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
