# Generated by Django 3.2 on 2022-06-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0008_alter_solicitudcuidados_costo'),
        ('solicitudes', '0008_alter_solicitudcuidadosfechas_tiempo'),
    ]

    operations = [
    ]
