# Generated by Django 3.2 on 2022-06-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0009_merge_20220609_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcuidados',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Recurrente'), (2, 'Por fecha')], default=1, verbose_name='Tipo de servicio'),
            preserve_default=False,
        ),
    ]
