# Generated by Django 3.2 on 2022-06-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0010_solicitudcuidados_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcuidados',
            name='recurrencia',
        ),
    ]
