# Generated by Django 3.2 on 2022-06-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0011_remove_solicitudcuidados_recurrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='tipo',
            field=models.IntegerField(choices=[(2, 'Por fecha'), (1, 'Recurrente')], verbose_name='Tipo de servicio'),
        ),
    ]
