# Generated by Django 3.2 on 2022-06-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0012_auto_20220613_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='tipo',
            field=models.CharField(default='Recurrente', max_length=17, verbose_name='Tipo de servico'),
        ),
    ]
