# Generated by Django 3.2 on 2022-06-15 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_alter_solicitudcuidados_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcuidados',
            options={'verbose_name_plural': 'Solicitudes de Cuidado recurrente'},
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='costo',
            field=models.FloatField(blank=True, default=0, help_text='El costo es semanal', verbose_name='Costo del servicio'),
        ),
        migrations.AlterField(
            model_name='solicitudcuidadosasignacion',
            name='solicitudCuidados',
            field=models.ForeignKey(limit_choices_to={'estado': 1}, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudcuidados'),
        ),
    ]
