# Generated by Django 3.2 on 2022-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0013_alter_solicitudcuidados_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcuidados',
            options={'verbose_name': 'Solicitud de cuidado recurrente', 'verbose_name_plural': 'Solicitudes de cuidado recurrente'},
        ),
        migrations.AlterModelOptions(
            name='solicitudcuidadosproxy',
            options={'verbose_name': 'Solicitud de cuidado por fecha', 'verbose_name_plural': 'Solicitud de cuidados por fecha'},
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='costo',
            field=models.FloatField(blank=True, default=0, help_text='El costo es semanal', verbose_name='Costo del servicio'),
        ),
    ]
