# Generated by Django 3.2 on 2022-06-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0015_alter_solicitudcuidados_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='tipo',
            field=models.CharField(default='Recurrente', max_length=17, verbose_name='Tipo de servico'),
        ),
    ]
