# Generated by Django 3.2 on 2022-06-15 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0016_alter_solicitudcuidados_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidadosasignacion',
            name='solicitudCuidados',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudcuidados'),
        ),
    ]
