# Generated by Django 3.2 on 2022-06-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0017_alter_solicitudcuidadosasignacion_solicitudcuidados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidadosasignacion',
            name='solicitudCuidados',
            field=models.ForeignKey(limit_choices_to={'estado': 1}, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.solicitudcuidados'),
        ),
    ]
