# Generated by Django 3.2 on 2022-06-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0014_auto_20220615_1054'),
        ('solicitudes', '0018_alter_solicitudcuidadosasignacion_solicitudcuidados'),
    ]

    operations = [
    ]
