# Generated by Django 3.2 on 2022-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0019_merge_20220622_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcuidados',
            name='adolecentes',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Asignada'), (3, 'Finalizada'), (4, 'Cancelada')], default=0),
        ),
        migrations.AddField(
            model_name='solicitudcuidados',
            name='infantes',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Asignada'), (3, 'Finalizada'), (4, 'Cancelada')], default=0),
        ),
        migrations.AddField(
            model_name='solicitudcuidados',
            name='preadolescentes',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Asignada'), (3, 'Finalizada'), (4, 'Cancelada')], default=0),
        ),
    ]
