# Generated by Django 3.2 on 2022-07-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0020_auto_20220704_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='adolecentes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='infantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='preadolescentes',
            field=models.IntegerField(default=0),
        ),
    ]
