# Generated by Django 3.2 on 2022-07-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0021_auto_20220704_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='adolecentes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='infantes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='preadolescentes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
