# Generated by Django 3.2 on 2022-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0025_alter_solicitudcuidados_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcuidados',
            name='tipo',
            field=models.CharField(choices=[('Recurrente', 'Recurrente'), ('Por fecha', 'Por fecha')], max_length=17, verbose_name='Tipo de servico'),
        ),
    ]
