# Generated by Django 4.0.3 on 2022-04-13 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('param', '0002_alter_ciudad_options_alter_pais_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, unique=True)),
                ('matricula', models.CharField(max_length=200, unique=True)),
                ('cuit', models.CharField(max_length=11, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param.ciudad')),
            ],
            options={
                'verbose_name_plural': 'Cooperativas',
            },
        ),
    ]
