# Generated by Django 3.2 on 2022-06-07 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coops', '0003_asociadx_caracteristica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asociadx',
            name='usuarix',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asociadx',
            name='cuit',
            field=models.CharField(max_length=11, unique=True, verbose_name='Cuil/Cuit'),
        ),
        migrations.AlterField(
            model_name='asociadx',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asociadx',
            name='ingreso',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='caracteristicacuidado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='caracteristicacuidado',
            name='icono',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviciocuidado',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviciocuidado',
            name='icono',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tiposervicio',
            name='icono',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
