# Generated by Django 3.2 on 2022-06-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0005_auto_20220606_1404'),
        ('coops', '0004_auto_20220607_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativa',
            name='ciudad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='param.ciudad'),
        ),
    ]
