# Generated by Django 4.0.4 on 2022-05-31 13:44

from django.db import migrations

from param.models import Ciudad


def crear_registro_inicial(apps, schema_editor):
    Cooperativa = apps.get_model("coops", "Cooperativa")

    Cooperativa.objects.create(razon_social='', matricula='',cuit='',direccion='',telefono='', email='')

class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0005_alter_cooperativa_ciudad'),
    ]

    operations = [
        migrations.RunPython(crear_registro_inicial)
    ]
