# Generated by Django 3.2 on 2022-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0006_auto_20220608_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativa',
            name='contraseña',
            field=models.CharField(default=1, max_length=20, verbose_name='Contraseña'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='host',
            field=models.CharField(default=1, max_length=10, verbose_name='Email host'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooperativa',
            name='port',
            field=models.IntegerField(default=1, verbose_name='Email port'),
            preserve_default=False,
        ),
    ]
