# Generated by Django 3.2 on 2022-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0007_auto_20220615_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativa',
            name='host',
            field=models.CharField(max_length=20, verbose_name='Email host'),
        ),
    ]
