# Generated by Django 3.2 on 2022-06-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coops', '0008_alter_cooperativa_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooperativa',
            name='host',
            field=models.CharField(max_length=30, verbose_name='Email host'),
        ),
    ]
