# Generated by Django 4.0.3 on 2022-04-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('param', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name_plural': 'Provincias'},
        ),
    ]
